"""add id column

Revision ID: ca5649693c93
Revises: c642371b77b2
Create Date: 2021-03-18 14:58:57.645903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca5649693c93'
down_revision = 'c642371b77b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")

    op.create_table(
        "user",
        sa.Column("id", sa.Integer, nullable=False, autoincrement=True),
        sa.Column("email", sa.String(length=128), nullable=False),
        sa.Column("password", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")

    op.create_table(
        "user",
        sa.Column("email", sa.String(length=128), nullable=False),
        sa.Column("password", sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint("email"),
    )
    # ### end Alembic commands ###